version: '3'
services:

  back-office-gateway:
    image: renvl/back-office-gateway
    build:
      context: ./back-office-gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - gateway-network

  conference-gateway:
    image: renvl/conference-gateway
    build:
      context: ./conference-gateway
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - gateway-network

  conference-platform:
    image: renvl/conference-platform
    build:
      context: ./conference-platform
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge
