server:
  port: 8082

spring:
  application:
    name: conference-gateway

  cloud:
    gateway:
      routes:
        - id: conference-available-route
          uri: http://conference-platform:8083
          predicates:
            - Method=POST
            - Path=/conference/available
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, Gateway Service
            - AddRequestHeader=Content-Type, application/json
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true