server:
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG

spring:
  application:
    name: back-office-gateway

  cloud:
    gateway:
      routes:
        - id: conference-room-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/conference-room
          filters:
            - AddResponseHeader=X-Powered-By, Gateway Service
            - AddRequestHeader=Content-Type, application/json
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true